language: java
sudo: false
jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk10
- openjdk8
- openjdk9
- openjdk10
script:
- ./gradlew check
- ./gradlew runFunctionalTest
notifications:
  slack:
    secure: SXnv/KuRr7tH1pq8CGhtgZt6RtlffSJR6uld3G36zpd2ozHEM1cjMQiY0sogPT5Xj0SSZ3apcs1G9DDb13UBz3goYYrd5rj4KIX++3PXgX9o+sP6g20Mo5lI4slFeKIfG/pERp9VZrk3epfzGXRBN+5H/l3nXEleznWPCbu8rTc=
